### PR TITLE
Fix offline mode not working

### PR DESCRIPTION
**Pull request by Powana**
Just a small typo, the order of the AuthCore arguments were swapped. This was also the source of the error I was having in #18

### CODE REVIEW

**Comment by Powana** [comment]
not changed: The `online_mode` argument for SimpleClient doesn't override the AuthPlugin default value of `online_mode=True`, meaning there also has to be an "auth" entry with `"online_mode":False` in the plugin `settings` dict if one wants to use offline mode. Not sure if intended or not.

**Comment by nickelpro** [comment]
Closing in favor of https://github.com/SpockBotMC/RikerBot/commit/d52739e3fea85a26535d912f624a1f4380acb847

**Comment by Powana** [comment]
Fair enough, but the order is still wrong. In AuthCore init the order is `online, timeout`, but on row 77 of AuthPlugin.py the plugin initializes in the core in the order `timeout, online_mode`.

**Comment by nickelpro** [comment]
That's because I am very stupid, thanks for the heads up

Fixed in https://github.com/SpockBotMC/RikerBot/commit/efe7e8c7ad897fc720f9fa8630010cd36c07ae93

**Comment by nickelpro** [comment]
Also just general thank you for tracking down all of these little bugs in login, much appreciated for making this work smoother

**Pull request closed without merging**
